### PR TITLE
Copy resources per pod

### LINKED ISSUE #500: duplicate PrivacyInfo.xcprivacy when build YandexMobileAds for iOS
Tested in Defold 1.9.3 and 1.9.4 beta and `build-stage.defold.com` server:

```
com.defold.extender.ExtenderException: java.nio.file.FileAlreadyExistsException: /var/folders/2b/mpxyl1m54jvg2rcs2cnbsqxc0000gn/T/job3653979061400368429/build/resources/PrivacyInfo.xcprivacy
	at com.defold.extender.Extender.buildEngine(Extender.java:2244)
	at com.defold.extender.Extender.build(Extender.java:2612)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:116)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.nio.file.FileAlreadyExistsException: /var/folders/2b/mpxyl1m54jvg2rcs2cnbsqxc0000gn/T/job3653979061400368429/build/resources/PrivacyInfo.xcprivacy
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at com.defold.extender.Extender.buildPods(Extender.java:983)
	at com.defold.extender.Extender.buildEngine(Extender.java:2214)
	... 14 more
```

Repo case project:
[test_yandex.zip](https://github.com/user-attachments/files/17291197/test_yandex.zip)

Full build log:
[log.txt_yandex_sdk.zip](https://github.com/user-attachments/files/17291191/log.txt_yandex_sdk.zip)

@Lerg any idea?

### PR DESCRIPTION
**Pull request by britzl**
This change copies the resources per pod to subfolders to avoid duplicate files, for example when more than one pod has a PrivacyInfo.xcprivacy file defined among its resources.

Also included in this change is that the resources are returned to the client for further processing (for instance resource bundles).

Fixes #500

### CODE REVIEW

File: server/src/main/java/com/defold/extender/Extender.java [hunk 1]
```diff
@@ -2448,6 +2458,10 @@ private List<File> buildApple(String platform) throws ExtenderException {
         LOGGER.info("Building Apple specific code");
         List<File> outputFiles = new ArrayList<>();
 
+        File resourceDirectory = new File(buildDirectory, "resources");
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:2461]: Add all pod resources to the output sent back to the client

**Review by AGulev — APPROVED** [review]
totally makes sense!
