### PR TITLE
Module support

### LINKED ISSUE #308: Building newer versions of Firebase for iOS faills
Newer versions of Firebase require module support. Adding -fmodules and -fcxx-modules results in error "cyclic dependency in module 'Darwin': Darwin -> std -> Darwin"

```
clang++ -c -arch arm64 -target arm-apple-darwin19 -m64 -O2 -g -stdlib=libc++ -miphoneos-version-min=11.0 -isysroot /Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk -nostdinc++ -isystem /Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/usr/include/c++/v1  -DDLIB_LOG_DOMAIN="FIREBASECORE" -DDDF_EXPOSE_DESCRIPTORS -DDM_PLATFORM_IOS -DDM_DEBUG -DFirebase_VERSION=10.12.0 -DCOCOAPODS=1  -fno-autolink -fobjc-arc --language=objective-c -fmodules -fmodule-name=FirebaseCore  -Iupload/ -Iupload/firebase/include/ -ICocoaPodsService/Pods/FirebaseCore/FirebaseCore/Sources/Public/FirebaseCore/ -ICocoaPodsService/Pods/FirebaseCore/FirebaseCore/Sources/Public/ -ICocoaPodsService/Pods/FirebaseCore/FirebaseCore/Sources/ -ICocoaPodsService/Pods/FirebaseCore/FirebaseCore/ -ICocoaPodsService/Pods/FirebaseCore/FirebaseCore/Extension/ -ICocoaPodsService/Pods/FirebaseCore/ -ICocoaPodsService/Pods/FirebaseCoreInternal/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsIDController/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Public/FirebaseInstallations/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Public/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Private/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsAPI/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/Errors/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/IIDMigration/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsStore/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseInstallations/Source/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseCore/Extension/ -ICocoaPodsService/Pods/FirebaseInstallations/FirebaseCore/ -ICocoaPodsService/Pods/FirebaseInstallations/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/Environment/Public/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/Environment/Public/ -ICocoaPodsService/Pods/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/Logger/Public/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/Logger/Public/ -ICocoaPodsService/Pods/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/NSData+zlib/Public/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/NSData+zlib/Public/ -ICocoaPodsService/Pods/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/UserDefaults/Public/GoogleUtilities/ -ICocoaPodsService/Pods/GoogleUtilities/GoogleUtilities/UserDefaults/Public/ -ICocoaPodsService/Pods/GoogleUtilities/ -ICocoaPodsService/Pods/PromisesObjC/Sources/FBLPromises/include/ -ICocoaPodsService/Pods/PromisesObjC/Sources/FBLPromises/ -ICocoaPodsService/Pods/PromisesObjC/ -ICocoaPodsService/frameworks/headers/arm64-ios/  -F/Users/bjornritzl/Downloads/EXTENDER/job1/CocoaPodsService/frameworks/lib/arm64-ios  -I/Users/bjornritzl/projects/defold/tmp/dynamo_home//include -I/Users/bjornritzl/projects/defold/tmp/dynamo_home//sdk/include -I/Users/bjornritzl/projects/defold/tmp/dynamo_home//ext/include   CocoaPodsService/Pods/FirebaseCore/FirebaseCore/Sources/FIRDependency.m -obuild/FIRDependency.m_7.o
While building module 'Foundation' imported from CocoaPodsService/Pods/FirebaseCore/FirebaseCore/Extension/FIRComponentType.h:17:
While building module 'CoreFoundation' imported from /Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'Darwin' imported from /Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
While building module 'std' imported from /Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/usr/include/tgmath.h:31:
In file included from <module-includes>:1:
/Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/usr/include/c++/v1/ctype.h:38:15: fatal error: cyclic dependency in module 'Darwin': Darwin -> std -> Darwin
#include_next <ctype.h>
```

### PR DESCRIPTION
**Pull request by britzl**
Fixes #308

### CODE REVIEW

File: server/src/main/java/com/defold/extender/Extender.java [hunk 1]
```diff
@@ -760,6 +760,14 @@ else if (platform.contains("osx")) {
         Map<String, Object> mergedContextWithPodsForObjC = ExtenderUtil.mergeContexts(trimmedContext, podContextObjC);
         Map<String, Object> mergedContextWithPodsForObjCpp = ExtenderUtil.mergeContexts(trimmedContext, podContextObjCpp);
 
+        // remove systemIncludes from objc and objc++
+        // this is a bit crude but cocoapod builds do not provide any -isystem option and
+        // it seems like the "{{env.SYSROOT}}/usr/include/c++/v1" set in build.yml is
+        // causing problems when building objc code with -fmodules enabled
```
Comment (JCash) [inline server/src/main/java/com/defold/extender/Extender.java:766]: Yes, we currently don't separate the C and C++ languages.
And C++ headers cannot be used in C languages (e.g. ObjC)

**Review by JCash — APPROVED** [review]
