### PR TITLE
Write source list to temp file and pass it as input to compile command

### LINKED ISSUE #701: Compilation failed if source path contains spaces
For example, Podfile with following content:
```
platform :ios, '13.0'
pod 'SuperwallKit', '3.3.2'
```

SuperwallKit spec is 
```
{
  "name": "SuperwallKit",
  "version": "3.3.2",
  "summary": "Superwall: In-App Paywalls Made Easy",
  "description": "Paywall infrastructure for mobile apps :) we make things like editing your paywall and running price tests as easy as clicking a few buttons. superwall.com",
  "homepage": "https://github.com/superwall-me/Superwall-iOS",
  "license": {
    "type": "MIT",
    "text": "\t\tMIT License\n\n\t\tCopyright (c) 2023 Superwall\n\n\t\tPermission is hereby granted, free of charge, to any person obtaining a copy\n\t\tof this software and associated documentation files (the \"Software\"), to deal\n\t\tin the Software without restriction, including without limitation the rights\n\t\tto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n\t\tcopies of the Software, and to permit persons to whom the Software is\n\t\tfurnished to do so, subject to the following conditions:\n\n\t\tThe above copyright notice and this permission notice shall be included in all\n\t\tcopies or substantial portions of the Software.\n\n\t\tTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n\t\tIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n\t\tFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n\t\tAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n\t\tLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n\t\tOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n\t\tSOFTWARE.\n"
  },
  "source": {
    "git": "https://github.com/superwall-me/Superwall-iOS.git",
    "tag": "3.3.2"
  },
  "authors": {
    "Jake Mor": "jake@superwall.com"
  },
  "documentation_url": "https://docs.superwall.com/",
  "swift_versions": [
    "5.5"
  ],
  "platforms": {
    "ios": "13.0"
  },
  "requires_arc": true,
  "source_files": "Sources/**/*.{swift}",
  "resources": [
    "Sources/SuperwallKit/**/*.xcassets",
    "Sources/SuperwallKit/**/*.xcdatamodeld",
    "Sources/SuperwallKit/**/*.cer"
  ],
  "swift_version": "5.5"
}

```

Source paths contains spaces, for example, `Pods/SuperwallKit/Sources/SuperwallKit/Paywall/View Controller/Web View/Templating/Models/Variables.swift`. Extender doesn't interpret it correctly.

### PR DESCRIPTION
**Pull request by ekharkunov**
Write list of source files list to temporary file in escape form. It helps avoid problem when `ProcessExecutor` split input string command by space and intepret as separate arguments.

Fixes #701

### CODE REVIEW

File: server/src/main/java/com/defold/extender/Extender.java [hunk 1]
```diff
@@ -596,10 +596,12 @@ private void emitSwiftHeader(PodSpec pod, Map<String, Object> manifestContext, L
         frameworkPaths.addAll(getFrameworkPaths(pod.dir));
         frameworkPaths.addAll(resolvedPods.getFrameworksSearchPaths());
 
+        File sourceListFile = ExtenderUtil.writeSourceFilesListToTmpFile(pod.swiftSourceFilePaths);
+
         Map<String, Object> context = createContext(manifestContext);
         context.put("ext", ImmutableMap.of("includes", includes, "frameworks", frameworks, "frameworkPaths", frameworkPaths));
         context.put("moduleName", pod.moduleName);
-        context.put("swiftSourceFiles", pod.swiftSourceFilePaths);
+        context.put("swiftSourceFiles", String.format("@%s", sourceListFile.getAbsolutePath()));
```
Comment (ekharkunov) [inline server/src/main/java/com/defold/extender/Extender.java:604]: Here and below: in Mustache template list expected. But If pass value as String - it works. It feels a bit incorrect to me but it works.

**Review by britzl — APPROVED** [review]
