### PR TITLE
Problem compiling YandexMobileAds

### LINKED ISSUE #298: Problem with YandexMobileAds cocoapods compilation
When trying to use cocoapods of yandex mobile ads, defold fails to properly integrate its frameworks.

```
ld: warning: Could not find or use auto-linked framework 'YandexMobileMetrica'
```

Podfile
```
platform :ios, '12.0'
pod 'YandexMobileAds', '5.2.1'
pod 'YandexMobileAdsInstream', '0.12.0'
```

[log.txt](https://github.com/defold/extender/files/11714448/log.txt)

### PR DESCRIPTION
**Pull request by britzl**
Fixed #298

### CODE REVIEW

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 1]
```diff
@@ -147,9 +147,9 @@ public void addAll(LanguageSet set) {
         public String toString() {
             StringBuilder sb = new StringBuilder();
             sb.append("c: " + c);
-            sb.append("cpp: " + cpp);
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:150]: Tidying up toStrings

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 2]
```diff
@@ -222,6 +222,7 @@ public class PodSpec {
         public Set<File> sourceFiles = new LinkedHashSet<>();
         public Set<File> includePaths = new LinkedHashSet<>();
         public PodSpec parentSpec = null;
+        public List<String> defaultSubspecs = new ArrayList<>();
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:225]: Keep track of defaultSubspecs (but not used at the moment)

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 3]
```diff
@@ -930,11 +925,15 @@ private List<PodSpec> installPods(File workingDir, Map<String, Object> jobEnvCon
                 specs.add(mainpod);
             }
             else {
-                String subspecname = podnameparts[1];
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:933]: A cocopoad can have hierarchies of dependencies, not only a parent and child relationship. Take this into account and add all subspecs.

**Review by AGulev — APPROVED** [review]
