### PR TITLE
Fixed Pod spec parsing

### LINKED ISSUE #684: Exception while parsing Podspec
```
java.lang.ClassCastException: class org.json.simple.JSONArray cannot be cast to class java.lang.String (org.json.simple.JSONArray is in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @7ef20235; java.lang.String is in module java.base of loader 'bootstrap')
	at com.defold.extender.services.CocoaPodsService.hasString(CocoaPodsService.java:658)
	at com.defold.extender.services.CocoaPodsService.parseConfig(CocoaPodsService.java:697)
	at com.defold.extender.services.CocoaPodsService.parseMultiPlatformConfig(CocoaPodsService.java:795)
	at com.defold.extender.services.CocoaPodsService.createPodSpec(CocoaPodsService.java:967)
	at com.defold.extender.services.CocoaPodsService.createPodSpec(CocoaPodsService.java:1175)
	at com.defold.extender.services.CocoaPodsService.installPods(CocoaPodsService.java:1301)
	at com.defold.extender.services.CocoaPodsService.resolveDependencies(CocoaPodsService.java:1366)
	at com.defold.extender.Extender.resolve(Extender.java:2748)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:116)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:114)
	at org.springframework.scheduling.concurrent.DelegatingErrorHandlingCallable.call(DelegatingErrorHandlingCallable.java:52)
	at io.micrometer.context.ContextSnapshot.lambda$wrap$1(ContextSnapshot.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```
More information: https://forum.defold.com/t/ios-and-cocoa-pod-issue/80152

### PR DESCRIPTION
**Pull request by ekharkunov**
Lot's of parts related to PodSpec were moved into separate classes for easier testing. All classes related to Cocoapods functionality were moved to `cocoapods` package.

Introduced new function `getStringListValues` which interpret input value as string with ' ' delimiter or as array of string. Also checks if `$(inherited)` is presented and removes it. Used new function for defines, flags and linker flags.

Added tests for pod spec parser.

Based on [issue-344-680-cocoapods-spec-repo](https://github.com/defold/extender/tree/issue-344-680-cocoapods-spec-repo) to avoid merge conflicts.

Fixes #684

### CODE REVIEW

File: server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java [hunk 1]
```diff
@@ -0,0 +1,754 @@
...
+    static void parseConfig(JSONObject config, LanguageSet flags, Set<String> linkflags, Set<String> defines) {
+        // https://pewpewthespells.com/blog/buildsettings.html
+        // defines
+        List<String> defs = getStringListValues(config, "GCC_PREPROCESSOR_DEFINITIONS");
+        if (defs != null) {
+            defines.addAll(unescapeStrings(defs));
+        }
+        // linker flags
+        // https://xcodebuildsettings.com/#other_ldflags
+        List<String> ldFlags = getStringListValues(config, "OTHER_LDFLAGS");
```
Comment (ekharkunov) [inline server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java:434]: Main fix. Now value can be string with ' ' as delimiter or array of strings.
Also removed `$(inherited)` value which not a valid value for linker (it's valid for xcode config files).

File: server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java [hunk 2]
```diff
@@ -0,0 +1,754 @@
...
+        }
+        if (compareString(config, "GCC_ENABLE_ASM_KEYWORD", "YES")) {
+            flags.add("-fasm");
+        }
+        if (compareString(config, "GCC_ENABLE_ASM_KEYWORD", "NO")) {
+            flags.add("-fno-asm");
+        }
+    }
+
+    static List<String> getStringListValues(JSONObject o, String key) {
```
Comment (ekharkunov) [inline server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java:532]: New function which interpret input value as string with ' ' delimeter or as array of string. Also checks if `$(inherited)` is presented and removes it.

**Review by britzl — APPROVED** [review]
