### PR TITLE
Fix how public headers are collected from PodSpec

### LINKED ISSUE #835: Google signin pod fails to build
From Discord post https://discord.com/channels/250018174974689280/819621765616500796/1461240732328398899:

BLISSY — 15.01.2026, 08:08
```
warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DLIB_LOG_DOMAIN="GTMAPPAUTH"')
<module-includes>:1:9: note: in file included from <module-includes>:1:
1 | #import "Headers/AppAuth-umbrella.h"
  |         `- note: in file included from <module-includes>:1:
2 | 

/var/folders/tn/5rwq3j0d41z37qlbh_15j9m80000gn/T/job15586929811132073425/CocoaPodsService/Pods/Target Support Files/AppAuth/AppAuth-umbrella.h:13:9: error: 'AppAuthCore.h' file not found
11 | #endif
12 | 
13 | #import "AppAuthCore.h"
   |         `- error: 'AppAuthCore.h' file not found
14 | #import "OIDAuthorizationRequest.h"
15 | #import "OIDAuthorizationResponse.h"
```

While integrating googlesignin on ios i get this error when building. I have no idea how to fix it. 
I tried adding appauth library in podfile and other dependencies of google signin and it still gives similar if not same error every single time .. ? 

Am i missing something ? 
Current manifest.ext:: 
```
name: "gsi"

platforms:
    armv7-android:
        context:
            jetifier: true
    arm64-android:
        context:
            jetifier: true
    arm64-ios:
        context:
            flags: ['-fcxx-modules', '-fmodules', '-fobjc-weak', '-Wno-module-import-in-extern-c']
            linkFlags:  ['-ObjC', '-Wl,-rpath,/usr/lib/swift', '-Wl,-rpath,@executable_path/Frameworks']
            libs:       ['swiftCompatibility51', 'swiftCompatibility50']

    x86_64-ios:
        context:
            flags: ['-fcxx-modules', '-fmodules', '-fobjc-weak', '-Wno-module-import-in-extern-c']
            linkFlags:  ['-ObjC', '-Wl,-rpath,/usr/lib/swift', '-Wl,-rpath,@executable_path/Frameworks']
            libs:       ['swiftCompatibility51', 'swiftCompatibility50']
```

Podfile: 
```
platform :ios, '13.0'
pod 'GoogleSignIn'
```

### PR DESCRIPTION
**Pull request by ekharkunov**
* If no `public_header_files` defined all headers from sources enumerated as public. It fixes what VFS overlay file contains in case of `GoogleSignIn` pod
* Collect source files from platform setting

Fixes #835

### CODE REVIEW

File: server/src/main/java/com/defold/extender/services/cocoapods/PodBuildSpec.java [hunk 1]
```diff
@@ -345,8 +345,16 @@ void addPodIncludePaths(String pattern) {
...
     void collectSourceFilesFromSpec(PodSpec spec) {
-        for (String pattern : spec.publicHeadersPatterns) {
-            this.publicHeaders.addAll(PodUtils.listFilesGlob(this.dir, pattern));
+        // if no public_header_files specified treat source headers as public
+        if (!spec.publicHeadersPatterns.isEmpty()) {
+            for (String pattern : spec.publicHeadersPatterns) {
+                this.publicHeaders.addAll(PodUtils.listFilesGlob(this.dir, pattern));
+            }
+        } else {
+            for (String pattern : spec.sourceFilesPatterns) {
```
Comment (ekharkunov) [inline server/src/main/java/com/defold/extender/services/cocoapods/PodBuildSpec.java:354]: If not `public_header_files` defined - collect headers from sources.

File: server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java [hunk 2]
```diff
@@ -141,6 +141,7 @@ public static PodSpec createPodSpec(JSONObject specJson, PodUtils.Platform selec
         // find source and header files
         // https://guides.cocoapods.org/syntax/podspec.html#source_files
         spec.sourceFilesPatterns.addAll(getAsList(specJson, "source_files"));
+        if (platformSettings != null) spec.sourceFilesPatterns.addAll(getAsList(platformSettings, "source_files"));
```
Comment (ekharkunov) [inline server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java:144]: Collect source files from platform settings (see AppAuth.json as example)

**Review by britzl — APPROVED** [review]
