### PR TITLE
Embedd dynamic frameworks

### LINKED ISSUE #274: [Cocoapods] Dynamic framework doesn't pack with application
Describe the problem
Some of ios framework links with target application in "dynamic" manner. It means that application should have "Frameworks/SomeLibrary.framework" inside application bundle.

Example
1. Use podfile like
```
platform :ios, '11.0'

pod 'HelpshiftX', '10.2.3'
```
2. Add to ext.manifest following lines
```
platforms:
    arm64-ios:
        context:
            linkFlags:  ['-Wl,-rpath,@executable_path/Frameworks']
```
3. Build and run application. Get following error during luanch
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dyld: Using shared cache: 9816A151-4D39-3378-B552-7BCA27A9DCB5 | dependent dylib '@rpath/HelpshiftX.framework/HelpshiftX' not found for '/private/var/containers/Bundle/Application/413FDAD0-9FA7-4D03-A419-2B9A9A5A2C19/sample-app.app/defoldhelpshift', tried but didn't find: '/private/var/containers/Bundle/Application/413FDAD0-9FA7-4D03-A419-2B9A9A5A2C19/sample-app.app/Frameworks/HelpshiftX.framework/HelpshiftX' '@rpath/HelpshiftX.framework/HelpshiftX' '/System/Library/Frameworks/HelpshiftX.framework/HelpshiftX'
Highlighted by Thread:  0
```

### PR DESCRIPTION
**Pull request by britzl**
Dynamic frameworks should be embedded into the final application bundle. This PR identifies such frameworks and returns them with the build results to the client.

Fixes #274

### CODE REVIEW

File: server/src/main/java/com/defold/extender/FrameworkUtil.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+     * @param framework The framework to check (eg Foo.framework) 
+     * @return true if dynamically linked
+     */
+    public static boolean isDynamicallyLinked(File framework) throws ExtenderException {
+        if (!framework.getName().endsWith(".framework")) {
+            throw new ExtenderException("File " + framework + " is not a framework");
+        }
+        String frameworkName = framework.getName().replace(".framework", "");
+        File frameworkBinary = new File(framework, frameworkName);
+        String output = execCommand("file " + frameworkBinary.getAbsolutePath());
```
[the remark this answers is not in the document]
Comment (JCash) [reply server/src/main/java/com/defold/extender/FrameworkUtil.java:42]: Perhaps a good code comment?

File: server/src/main/java/com/defold/extender/Extender.java [hunk 2]
```diff
@@ -741,34 +742,65 @@ else if (extension.equals("m") || extension.equals("mm")) {
...
+                File lib = createBuildFile(String.format(platformConfig.writeLibPattern, manifestContext.get("extension_name") + "_" + getNameUUID()));
+                Map<String, Object> context = createContext(manifestContext);
+                context.put("tgt", lib);
+                context.put("objs", objs);
+                String command = templateExecutor.execute(platformConfig.libCmd, context);
+                processExecutor.execute(command);
+            }
+        }
+
+        LOGGER.info("buildPods - adding dynamic frameworks to build output");
```
Comment (JCash) [inline server/src/main/java/com/defold/extender/Extender.java:777]: Candidate for a new function

File: server/src/main/java/com/defold/extender/Extender.java [hunk 3]
```diff
@@ -741,34 +742,65 @@ else if (extension.equals("m") || extension.equals("mm")) {
     }
 
     // build the source files of each resolved pod file into a library
-    private void buildPods() throws IOException, InterruptedException, ExtenderException {
+    private List<File> buildPods() throws IOException, InterruptedException, ExtenderException {
+        List<File> outputFiles = new ArrayList<>();
+        if (resolvedPods == null) {
+            LOGGER.info("buildPods - no pods");
+            return outputFiles;
+        }
```
Comment (JCash) [inline server/src/main/java/com/defold/extender/Extender.java:750]: 👍  for early outs!

**Review by JCash — APPROVED** [review]
