### PR TITLE
Consume http response in case of HTTP error

### LINKED ISSUE #528: Help Bob.jar output a more friendly error message from the server about why it failed on user/pass
When setting user/pass wrong, all you get is this:

````
'x86_64-ps4' could not be built. Sdk version: 'abcdef123345567678'
Log: '<failed reading log>'
Cause: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
2024-10-17 08:53:29 SEVERE  'x86_64-ps4' could not be built. Sdk version: 'abcdef123345567678'
Log: '<failed reading log>
```

### PR DESCRIPTION
**Pull request by ekharkunov**
* Possible problem was that response for `/query` returns HTTP error and Extender doesn't consume response stream.
* Replace `DefaultHttpClient` with preconfigured http client.
* Http client now stop sending request body if server returns one of 4XX code (https://lists.apache.org/thread/p38b3lrjt4vhyqthwhqcq3vsx3dpr3wj)
* Remove ExtenderClient constructor which accepts http client as argument.
* Add traceId to log file.
* Improve log file content in case of non-compilation error.

Fixes #528

### CODE REVIEW

File: client/src/test/java/com/defold/extender/client/ExtenderClientTest.java [hunk 1]
```diff
@@ -373,6 +377,50 @@ public CloseableHttpResponse execute(HttpUriRequest request) {
         }
     }
 
+    @Test(expected = ExtenderClientException.class)
+    public void testClientHandleHTTPError() throws ClientProtocolException, IOException, ExtenderClientException {
```
Comment (ekharkunov) [inline client/src/test/java/com/defold/extender/client/ExtenderClientTest.java:381]: Can't make the same simulation as it provided in initial issue. But at least now we have the test for HTTP error handling.

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 2]
```diff
@@ -223,7 +221,7 @@ private static Set<String> getCachedFiles(String json) throws ExtenderClientExce
     }
 
 
-    private void build_async(String platform, String sdkVersion, MultipartEntity entity, File destination, File log) throws ExtenderClientException {
+    private void build_async(String platform, String sdkVersion, HttpEntity entity, File destination, File log) throws ExtenderClientException {
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:224]: Replace deprecated type.

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 3]
```diff
@@ -63,25 +67,18 @@ public class ExtenderClient {
...
         this.extenderBaseUrl = extenderBaseUrl;
         this.cache = new ExtenderClientCache(cacheDir);
         this.httpCookies = new BasicCookieStore();
         this.buildSleepTimeout = Long.parseLong(System.getProperty("com.defold.extender.client.build-sleep-timeout", "5000"));
         this.buildResultWaitTimeout = Long.parseLong(System.getProperty("com.defold.extender.client.build-wait-timeout", "1200000"));
         this.headers = new ArrayList<BasicHeader>();
-        this.httpClient = httpClient;
-        this.httpClient.setCookieStore(httpCookies);
+        RequestConfig requestConfig = RequestConfig.custom()
+            .setExpectContinueEnabled(true).build();
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:77]: Second part of the fix. HTTP client waits 100 Continue from server side in case of additional authentication before sending request body. It helps avoid `Broken pipe` error, when client received 401 on `/build**` and tried push request body.

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 4]
```diff
@@ -190,6 +187,7 @@ String queryCache(List<ExtenderResource> sourceResources) throws ExtenderClientE
             if (response.getStatusLine().getStatusCode() == HttpStatus.SC_OK) {
                 return EntityUtils.toString(response.getEntity()).replace("\\/", "/");
             } else {
+                EntityUtils.consumeQuietly(response.getEntity());
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:190]: First part of the fix. In case of any error on `/query` request we need to consume response body to be sure that all data was read from the socket and connection can be reused in the future.

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 5]
```diff
@@ -267,12 +266,19 @@ private void build_async(String platform, String sdkVersion, MultipartEntity ent
                     response.getEntity().writeTo(new FileOutputStream(destination));
                 } else {
                     log("Job %s did not complete successfully. Writing log to %s", jobId, log);
-                    response.getEntity().writeTo(new FileOutputStream(log));
-                    throw new ExtenderClientException("Failed to build source.");
+                    OutputStream os = new FileOutputStream(log);
+                    os.write(String.format("Job id: %s; traceId: %s", jobId, traceId == null ? "null" : traceId).getBytes());
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:270]: Write to the log file information about `jobId` and `traceId` to easier debug user's requests about failed builds.

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 6]
```diff
@@ -267,12 +266,19 @@ private void build_async(String platform, String sdkVersion, MultipartEntity ent
...
+                    os.close();
+                    throw new ExtenderClientException(String.format("Failed to build source: jobId - %s, traceId - %s", jobId, traceId == null ? "null" : traceId));
                 }
             } else {
-                log("Async build request failed with status code %d", statusCode);
-                response.getEntity().writeTo(new FileOutputStream(log));
+                String result = String.format("Async build request failed with status code %d %s", statusCode, statusLine.getReasonPhrase());
+                log(result);
+                OutputStream os = new FileOutputStream(log);
+                os.write(result.getBytes());
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:279]: Write to the log file HTTP response code and error reason. It also helps to clear log file from previous results in case of empty response body (previously it can contains results from old build that can confuse users).

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 7]
```diff
@@ -281,7 +287,7 @@ private void build_async(String platform, String sdkVersion, MultipartEntity ent
 
     }
 
-    private void build_sync(String platform, String sdkVersion, MultipartEntity entity, File destination, File log) throws ExtenderClientException {
+    private void build_sync(String platform, String sdkVersion, HttpEntity entity, File destination, File log) throws ExtenderClientException {
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:290]: Replace deprecated type.

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 8]
```diff
@@ -338,7 +348,8 @@ public void build(String platform, String sdkVersion, List<ExtenderResource> sou
             return;
         }
 
-        MultipartEntity entity = new MultipartEntity();
+        MultipartEntityBuilder entityBuilder = MultipartEntityBuilder.create();
+        entityBuilder.setStrictMode();
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:352]: The same settings as it was before in `MultipartEntity` constructor;

File: client/src/main/java/com/defold/extender/client/ExtenderClient.java [hunk 9]
```diff
@@ -295,8 +301,12 @@ private void build_sync(String platform, String sdkVersion, MultipartEntity enti
             if (response.getStatusLine().getStatusCode() == HttpStatus.SC_OK) {
                 response.getEntity().writeTo(new FileOutputStream(destination));
             } else {
-                response.getEntity().writeTo(new FileOutputStream(log));
-                throw new ExtenderClientException("Failed to build source.");
+                String traceId = response.getFirstHeader(TRACE_ID_HEADER_NAME).getValue();
+                OutputStream os = new FileOutputStream(log);
+                os.write(String.format("TraceId: %s", traceId == null ? "null" : traceId).getBytes());
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/ExtenderClient.java:306]: Add some useful information to the log file for synchronous builds.

File: client/src/main/java/com/defold/extender/client/FileExtenderResource.java [hunk 10]
```diff
@@ -7,7 +7,6 @@
 public class FileExtenderResource implements ExtenderResource {
     private File file = null;
     private String filePath;
-    private String fileAbsPath;
```
Comment (ekharkunov) [inline client/src/main/java/com/defold/extender/client/FileExtenderResource.java:10]: Never used.

File: client/src/test/java/com/defold/extender/client/ExtenderClientTest.java [hunk 11]
```diff
@@ -358,7 +364,12 @@ public CloseableHttpResponse execute(HttpUriRequest request) {
             final String HDR_VALUE_2 = "my custom header2";
             MockHttpClient httpClient = new MockHttpClient();
             File cacheDir = new File("build");
-            ExtenderClient extenderClient = new ExtenderClient(httpClient, "http://localhost", cacheDir);
+            Class<?> mockExtenderClientClass = Class.forName("com.defold.extender.client.ExtenderClient");
```
Comment (ekharkunov) [inline client/src/test/java/com/defold/extender/client/ExtenderClientTest.java:367]: Because of remove constructor with `httpClient` as argument we need to workaround and set private field in mocked instance.
