### PR TITLE
Fix issues building certain combinations of pod dependencies

### LINKED ISSUE #403: Can't build YandexMobileAds for iOS
Yandex released a new version of their SDK, plus Defold has been updated so I tried building again with Defold 1.9.1 beta and YandexMobileAds 7.1.1

It still doesn't build but the error message has changed, now it complains about iOS SDK version not being at least 13, however it is set to be so in the Podfile:
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.1.1'
pod 'YandexMobileAdsMediation', '7.1.1'
```

Thee new error:
```
/var/folders/pf/6r_png356xb4lby2dkvym42r0000gn/T/job9582903447976259256/CocoaPodsService/Pods/DivKit/DivKit/Views/DivBlockProvider.swift:77:5: error: concurrency is only available in iOS 13.0.0 or newer
  ) async {
    ^
/var/folders/pf/6r_png356xb4lby2dkvym42r0000gn/T/job9582903447976259256/CocoaPodsService/Pods/DivKit/DivKit/Views/DivBlockProvider.swift:74:8: note: add @available attribute to enclosing instance method
  func setSource(
       ^
```

Full build log
[log.txt.zip](https://github.com/user-attachments/files/16193483/log.txt.zip)

The same result with bob.jar

### PR DESCRIPTION
**Pull request by britzl**
This issue fixes issues when building for instance the Yandex SDK

Fixes #403

### CODE REVIEW

File: server/src/main/java/com/defold/extender/Extender.java [hunk 1]
```diff
@@ -561,7 +561,7 @@ private List<String> getIncludeDirs(File extDir) {
     // swiftc: https://gist.github.com/enomoto/7f11d57e4add7e702f9f84f34d3a0f8c
     // swift-frontend: https://gist.github.com/palaniraja/b4de1e64e874b68bda9e5236829cd8a6
 
-    private void emitSwiftHeaders(PodSpec pod, Map<String, Object> manifestContext, List<String> commands) throws IOException, InterruptedException, ExtenderException {
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:564]: Grammar. We're emitting one header, not multiple.

File: server/src/main/java/com/defold/extender/Extender.java [hunk 2]
```diff
@@ -862,51 +862,77 @@ else if (platform.contains("osx")) {
...
         mergedContextWithPodsForSwift.put("systemIncludes", new ArrayList<String>());
-
+        // also clearing systemIncludes for c
+        // see https://github.com/defold/extender/issues/389
+        mergedContextWithPodsForC.put("systemIncludes", new ArrayList<String>());
 
         List<String> objs = new ArrayList<>();
 
         if (!pod.swiftSourceFiles.isEmpty()) {
+            // Add -enable-experimental-feature AccessLevelOnImport
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:872]: Like the comment says, an improvement for the future would be to add swiftFlags to ext.manifest so that additional swift flags can be added per extension.

File: server/src/main/java/com/defold/extender/Extender.java [hunk 3]
```diff
@@ -862,51 +862,77 @@ else if (platform.contains("osx")) {
...
+            List<String> updatedSwiftFlags = new ArrayList<String>(swiftFlags);
+            updatedSwiftFlags.add("-enable-experimental-feature");
+            updatedSwiftFlags.add("AccessLevelOnImport");
+            mergedContextWithPodsForSwift.put("swiftFlags", updatedSwiftFlags);
+
             // generate headers from swift files
             List<String> emitSwiftHeaderCommands = new ArrayList<>();
-            emitSwiftHeaders(pod, mergedContextWithPodsForC, emitSwiftHeaderCommands);
+            LOGGER.info("emit swift header");
+            emitSwiftHeader(pod, mergedContextWithPodsForSwift, emitSwiftHeaderCommands);
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:885]: Use the correct context, use mergedContextWithPodsForSwift not mergedContextWithPodsForC

File: server/src/main/java/com/defold/extender/Extender.java [hunk 4]
```diff
@@ -862,51 +862,75 @@ else if (platform.contains("osx")) {
...
+            emitSwiftModule(pod, mergedContextWithPodsForSwift, emitSwiftModuleCommands);
             ProcessExecutor.executeCommands(processExecutor, emitSwiftModuleCommands); // in parallel
 
             // compile swift source files one by one
             List<String> compileSwiftCommands = new ArrayList<>();
             for (File src : pod.swiftSourceFiles) {
-                final int i = getAndIncreaseNameCount();
-                File o = addCompileFileSwift(pod, i, src, mergedContextWithPodsForC, compileSwiftCommands);
-                objs.add(ExtenderUtil.getRelativePath(jobDirectory, o));
+                if (!podSourceLookup.contains(src)) {
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:897]: Some pods with multiple subspecs have source file mappings covering the same source files. This will result in duplicate symbols when linking. We avoid this by tracking which files we have already compiled.

File: server/src/main/java/com/defold/extender/Extender.java [hunk 5]
```diff
@@ -931,15 +957,17 @@ private List<File> buildPods() throws IOException, InterruptedException, Extende
             manifestContext.put("extension_name", pod.name);
             manifestContext.put("extension_name_upper", pod.name.toUpperCase());
             manifestContext.put("osMinVersion", resolvedPods.platformMinVersion);
+            manifestContext.put("env.IOS_VERSION_MIN", resolvedPods.platformMinVersion);
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:960]: We forgot to also set the env variable on the context

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 6]
```diff
@@ -40,6 +41,29 @@
...
+            sb.append("file: " + file);
+            sb.append("pod count: " + podnames.size() + "\n");
+            sb.append("pod names: " + podnames + "\n");
+            sb.append("platform: " + platform + "\n");
+            sb.append("min version: " + platformMinVersion + "\n");
+            return sb.toString();
+        }
+    }
+
+    private class InstalledPods {
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:62]: Same, small container class to hold list and mapping of resolved pods

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 7]
```diff
@@ -850,28 +907,47 @@ private String createOsxModuleMap(PodSpec pod, File jobDir) throws ExtenderExcep
         return moduleMapFile.getAbsolutePath();
     }
 
+
+    private String toC99extIdentifier(String s) {
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:911]: Convert a podname to a valid identifier

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 8]
```diff
@@ -850,28 +907,47 @@ private String createOsxModuleMap(PodSpec pod, File jobDir) throws ExtenderExcep
...
+        return s.replaceAll("^([0-9])", "_$1")  // 123FooBar -> _123FooBar
+            .replaceAll("[\\+].*", "")          // NSData+zlib -> NSData
+            .replaceAll("[^a-zA-Z0-9_]", "_")   // Foo-Bar -> Foo_Bar
+            .replaceAll("_+", "_");             // Foo__Bar -> Foo_Bar
+    }
+
+    // It seems like some exceptions such as KSCrash use a module name
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:918]: This is not pretty and will require further investigation at some point

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 9]
```diff
@@ -850,28 +907,47 @@ private String createOsxModuleMap(PodSpec pod, File jobDir) throws ExtenderExcep
...
+            return toC99extIdentifier((String)specJson.get("header_dir"));
+        }
+
+        String name = (String)specJson.get("name");
+        String fixedName = toC99extIdentifier(name);
+        if (parent == null) {
+            return fixedName;
+        }
+
+        return parent.name + (NAME_EXCEPTIONS.contains(parent.name) ? "" : "_") + fixedName;
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:939]: Main spec: KSCrash Sub spec: Recording -> KSCrashRecording
Main spec: GoogleUtilities Sub spec: NSData+zlib -> GoogleUtilities_NSData

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 10]
```diff
@@ -1267,19 +1350,19 @@ public ResolvedPods resolveDependencies(PlatformConfig config, File jobDir, Stri
 
         // find all podfiles and filter down to a list of podfiles specifically
         // for the platform we are resolving pods for
-        List<File> allPodFiles = ExtenderUtil.listFilesMatchingRecursive(jobDir, "Podfile");
-        List<File> platformPodFiles = new ArrayList<>();
-        for (File podFile : allPodFiles) {
+        List<File> allPodfiles = ExtenderUtil.listFilesMatchingRecursive(jobDir, "Podfile");
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:1353]: Grammar. It is called a Podfile, not a PodFile

**Review by AGulev — APPROVED** [review]
👍
