### PR TITLE
Handle non boolean values for requires arc option

### LINKED ISSUE #262: Handle non-boolean values for requires_arc in Podspecs
It turns out that the `requires_arc` option in a Podspec can be not only boolean but also a string or an array:

https://guides.cocoapods.org/syntax/podspec.html#requires_arc

In CocoapodsService we assume it is a boolean which throws an exception if the option is a string or array:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at com.defold.extender.services.CocoaPodsService.createPodSpec(CocoaPodsService.java:420)
	at com.defold.extender.services.CocoaPodsService.createPodSpec(CocoaPodsService.java:482)
	at com.defold.extender.services.CocoaPodsService.installPods(CocoaPodsService.java:548)
	at com.defold.extender.services.CocoaPodsService.resolveDependencies(CocoaPodsService.java:589)
	at com.defold.extender.Extender.resolve(Extender.java:2165)
	at com.defold.extender.ExtenderController.buildEngine(ExtenderController.java:224)
	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
```

### PR DESCRIPTION
**Pull request by britzl**
This PR also includes a fix for missing `env` in the context (this issue popped up after the big refactor @JCash did).

Fixes #262

### CODE REVIEW

File: server/scripts/standalone/publish-standalone.sh [hunk 1]
```diff
@@ -10,8 +10,8 @@ build_artifact() {
     echo "[build]  Creating standalone extender server artifact at ${ARTIFACT_DIR}..."
     rm -rf ${ARTIFACT_DIR}
     mkdir -p ${ARTIFACT_DIR}
-    cp ${SERVER_DIR}/build/docker/extender-0.1.0.jar ${ARTIFACT_DIR}/extender.jar
```
Comment (britzl) [inline server/scripts/standalone/publish-standalone.sh:13]: We should use the path for standalone builds. The jar files are copied in build.gradle in task `buildStandalone()`

File: server/src/main/java/com/defold/extender/Extender.java [hunk 2]
```diff
@@ -703,6 +703,9 @@ private void buildPods() throws IOException, InterruptedException, ExtenderExcep
                 // We use the same mechanism as when building the extension and create a
                 // manifest context for each pod
                 Map<String, Object> manifestContext = new HashMap<>();
+                manifestContext = ExtenderUtil.mergeContexts(manifestContext, this.platformConfig.context);
+                manifestContext = ExtenderUtil.mergeContexts(manifestContext, this.platformVariantConfig.context);
+                manifestContext = ExtenderUtil.mergeContexts(manifestContext, this.platformAppConfig.context);
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/Extender.java:708]: I think we want the platformAppConfig as well?

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 3]
```diff
@@ -578,14 +588,20 @@ public ResolvedPods resolveDependencies(File jobDirectory, String platform) thro
             throw new ExtenderException("Unsupported platform " + platform);
         }
 
+        List<File> podFiles = ExtenderUtil.listFilesMatchingRecursive(jobDirectory, "Podfile");
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:591]: Exit the service early if the job doesn't contain any Podfiles

File: server/src/main/java/com/defold/extender/Extender.java (hunk 2 above)
Comment (JCash) [reply server/src/main/java/com/defold/extender/Extender.java:708]: Why not use the already merged `mergedAppContext` from loadManifests() ?
You can make a copy of that and then override your variables below.

**Review by JCash — CHANGES_REQUESTED** [review]

File: server/src/main/java/com/defold/extender/Extender.java (hunk 2 above)
Comment (britzl) [reply server/src/main/java/com/defold/extender/Extender.java]: Good point! Done!

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 4]
```diff
@@ -338,17 +338,29 @@ private void copyPodFrameworks(List<PodSpec> pods, File frameworksDir) throws IO
                 File frameworkDir = new File(pod.dir, framework);
                 String frameworkName = frameworkDir.getName().replace(".xcframework", "");
                 
-                File armFrameworkDir = new File(frameworkDir, "ios-arm64_armv7");
-                if (armFrameworkDir.exists()) {
-                    Path from = new File(armFrameworkDir, frameworkName + ".framework").toPath();
+                File arm64_armv7FrameworkDir = new File(frameworkDir, "ios-arm64_armv7");
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:341]: Make sure to look for multiple variations of folder names inside the frameworks

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 5]
```diff
@@ -618,7 +617,7 @@ public ResolvedPods resolveDependencies(File jobDirectory, String platform) thro
         List<PodSpec> pods = installPods(workingDir);
         copyPodFrameworks(pods, frameworksDir);
         
-        dumpDir(jobDirectory, 0);
+        // dumpDir(jobDirectory, 0);
```
Comment (JCash) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java]: There is a DM_KEEP_JOB_FOLDER for debugging.
I suggest we piggyback on that?

**Review by JCash — APPROVED** [review]
