### PR TITLE
Fix platform version regex to handle osx

### LINKED ISSUE #351: osx podfile installation fails
With a podfile beginning with a line such as
`platform :osx '10.13'`

building for osx fails with this error:

```
java.lang.NumberFormatException: For input string: "platform : 10"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.defold.extender.services.CocoaPodsService.compareVersions(CocoaPodsService.java:351)
	at com.defold.extender.services.CocoaPodsService.createMainPodFile(CocoaPodsService.java:395)
	at com.defold.extender.services.CocoaPodsService.resolveDependencies(CocoaPodsService.java:1261)
	at com.defold.extender.Extender.resolve(Extender.java:2475)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:110)
	at com.defold.extender.AsyncBuilder$$FastClassBySpringCGLIB$$3a887347.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by dri-richard**
Fixes #351

### CODE REVIEW

File: server/src/main/java/com/defold/extender/services/CocoaPodsService.java [hunk 1]
```diff
@@ -391,7 +391,7 @@ private String createMainPodFile(List<File> podFiles, File jobDirectory, File wo
             List<String> lines = Files.readAllLines(podFile.getAbsoluteFile().toPath());
             for (String line : lines) {
                 if (line.startsWith("platform :")) {
-                    String version = line.replaceFirst("platform :ios|osx", "").replace(",", "").replace("'", "").trim();
+                    String version = line.replaceFirst("platform :ios|platform :osx", "").replace(",", "").replace("'", "").trim();
```
Comment (britzl) [inline server/src/main/java/com/defold/extender/services/CocoaPodsService.java:394]: I'm a bit confused by the change. I don't see how this change will make any difference? At least not with the example string given in the issue.
```java
public class Main {
  public static void main(String[] args) {
    String line = "platform :ios '10.13'";    
    String version = line.replaceFirst("platform :ios|osx", "").replace(",", "").replace("'", "").trim();
    System.out.println("version: " + version);    // version: 10.13
  }
}
```

Comment (britzl) [reply server/src/main/java/com/defold/extender/services/CocoaPodsService.java:394]: Ah, no, never mind me. I tested with the wrong string

```java
public class Main {
  public static void main(String[] args) {
    String line = "platform :osx '10.13'";     
    String version = line.replaceFirst("platform :ios|osx", "").replace(",", "").replace("'", "").trim();
    System.out.println("version: " + version);   // version: platform : 10.13
  }
}
```

The regex could be changed to `"platform :(ios|osx)"` but it doesn't really matter much.

**Review by britzl — APPROVED** [review]
